language: node_js
node_js:
  - 'lts/*'

env:
  global:
    - CC_TEST_REPORTER_ID=4b8ac4232bb1a3b0a85db670d2b72b6d6590c02e9c321588af790fb1d87a23aa

install:
  - npm install
  - lerna bootstrap

jobs:
  include:
    - stage: test
      if: tag IS blank
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - wget http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz
        - tar -xvf lcov-1.13.tar.gz
        - cd lcov-1.13 && sudo make install
        - cd ..
        - chmod +x ./merge_lcov.sh
      script:
        - lerna run test --parallel
        - ./merge_lcov.sh
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov
        - ./cc-test-reporter format-coverage -t lcov ./lcov.info
        - ./cc-test-reporter upload-coverage
